@startuml

class IHubController {
}
IHubController <|-- I2CHubController
IHubController <|-- UsbHubController

class HubManager {

}

HubManager "+1" o-- "+1..*" IHubController : Contins

class HttpServer {

}

HttpServer "+1" -- "+1" HubManager

@enduml